<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sass</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\/\*</string>
	<key>foldingStopMarker</key>
	<string>\*\/</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>Sass4as</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\/\*.*\*\/</string>
			<key>name</key>
			<string>comment.line.sass4as</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\/\*</string>
			<key>end</key>
			<string>\*\/</string>
			<key>name</key>
			<string>comment.block.sass4as</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(color|text-(?:indent|decoration|align)|display|kerning|font-(?:s(?:tyle|ize)|family|weight)|le(?:tter-spacing|ading)|margin-(?:left|right))\b</string>
			<key>name</key>
			<string>keyword.attribute.sass4as</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[a-zA-Z0-9\-]+</string>
			<key>name</key>
			<string>entity.name.tag.sass4as</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.sass4as</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.reference.sass4as</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^  (@extend) ([a-zA-Z0-9\-]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.declaration.sass4as</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\$[a-zA-Z0-9\-]+):</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$[a-zA-Z0-9\-]+$</string>
			<key>name</key>
			<string>variable.other.reference.sass4as</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#[a-fA-F0-9]{6}</string>
			<key>name</key>
			<string>constant.color.sass4as</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\d\.]+(p(t|x)|em)</string>
			<key>name</key>
			<string>constant.font-size.sass4as</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\t+</string>
			<key>name</key>
			<string>invalid.illegal.spacing.sass4as</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;</string>
			<key>name</key>
			<string>invalid.illegal.character.sass4as</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(s(erif|ans-serif)|center|no(ne|rmal)|true|i(nline|talic)|underline|justify|false|left|right|mono|b(old|lock))\b</string>
			<key>name</key>
			<string>support.constant.sass4as</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.sass4as</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.sass4as</string>
	<key>uuid</key>
	<string>3047ACB7-2A58-4018-BC51-5C60E77AA19E</string>
</dict>
</plist>
